import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import MainLayout from "components/layout/MainLayout";
import LoginLayout from "components/layout/LoginLayout";
import LoginForm from "components/screens/LoginForm";

export default function Home() {
  return (
    <div>
      <Head>
        <title>ISTOPP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <LoginLayout>
        <LoginForm variant="h4" />
      </LoginLayout>
    </div>
  );
}
