import { FormControl, MenuItem, OutlinedInput, Select, TextField, Typography } from '@mui/material'
import { Box } from '@mui/system'
import Head from 'next/head'
import Image from 'next/image'
import InputField from '../components/UI/InputField';

export default function Home() {


  const dateRange = [
    'Nov 1, 2022',
    'Nov 2, 2022',
    'Nov 3, 2022',
    'Nov 4, 2022',
    'Nov 5, 2022',
    'Nov 6, 2022',
    'Nov 7, 2022',
    'Nov 8, 2022',
    'Nov 9, 2022',
  ];

  return (
    <div className='container'>
      <Head>
        <title>ISTOPP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    </div>
  )
}
